name: sync-fork

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync repository
        uses: actions/checkout@v4
      - name: Sync fork
        run: gh repo sync -b master
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
